name: testapp
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI / Styling
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  photo_view: ^0.14.0

  # Story Flipbook (use this only)
  turn_page_transition: ^0.5.0

  # Storage / Images
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  lottie: ^3.3.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  # Authentication Options
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^7.0.1

  # Google Cloud TTS
  googleapis_auth: ^1.6.0
  googleapis: ^11.4.0

  # Audio + Speech
  just_audio: ^0.10.5
  audio_session: any
  speech_to_text: ^7.3.0
  visibility_detector: ^0.3.0

  # Utility / Networking
  http: ^1.4.0
  shared_preferences: ^2.2.2 # Bookmarking stories
  provider: ^6.1.1
  path_provider: ^2.1.5
  translator: ^1.0.4+1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/
    - assets/config/profanity_blocklist.json
    - assets/google_service_account.json
